# Generated by Django 3.0.5 on 2020-07-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('popularity', models.DecimalField(decimal_places=1, max_digits=3)),
                ('director', models.CharField(max_length=50)),
                ('genre', models.TextField()),
                ('imdb_score', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
