# Generated by Django 3.0.5 on 2020-07-28 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('displaymovies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='displaymovies',
            options={'verbose_name': 'Status post', 'verbose_name_plural': 'Status posts'},
        ),
    ]
