# Generated by Django 3.0.5 on 2020-07-28 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('displaymovies', '0002_auto_20200729_0137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='displaymovies',
            options={'verbose_name': 'Movie Details', 'verbose_name_plural': 'Movies Details'},
        ),
    ]
