# Generated by Django 3.0.5 on 2020-07-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displaymovies', '0003_auto_20200729_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaymovies',
            name='genre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='displaymovies',
            name='imdb_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='displaymovies',
            name='popularity',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
